### ISSUE TITLE
Bug - Login page not redirecting to Dashboard after login

### ISSUE THREAD

**Issue by d1pakda5** [yogeshojha/rengine#101]
Hi
just updated to V3 and the login page not redirecting to the dashboard even after navigating manually to /Dashboard its prompting for login again 

<img width="960" alt="Screenshot_41" src="https://user-images.githubusercontent.com/17035598/88207454-71256880-cc6d-11ea-9155-940eb5a74a8b.png">

**Comment by yogeshojha** [comment]
This could have happened due to the migration. Can you please delete any older container and start the fresh install?

`docker system prune -a`

Remove all volumes

`docker volume rm -f $(docker volume ls -q)`

With the fresh install, you should not have any problem. I am also checking on my end, I will upload on my VPS and see if things are not working there. Give me some time.

**Comment by yogeshojha** [comment]
Not sure, why it is not working at your end. I tried on my VPS and is working. Please delete rengine_web_1 container and  rengine_postgres_data volume. It should work without any problem, but please keep me updated on this. This is unusual, not working at your end.

**Comment by d1pakda5** [comment]
I tried all step you mentioned , did a fresh install  still facing the issue

<img width="957" alt="Screenshot_42" src="https://user-images.githubusercontent.com/17035598/88209673-b26b4780-cc70-11ea-886e-a914faca72a1.png">

**Comment by yogeshojha** [comment]
No worries, I will help you. Please email me 

yogesh.ojha11@gmail.com

I will connect via TeamViewer and figure it out.

**Comment by d1pakda5** [comment]
Sure @yogeshojha
