### ISSUE TITLE
Feature - use wappalyzer for fingerprint

### ISSUE THREAD

**Issue by abuvanth** [yogeshojha/rengine#179]
cli here - https://www.npmjs.com/package/wappalyzer

**Comment by RapidEU** [comment]
I thought of that and I even twitted about it, the thing is, aquatone is already doing fingerprinting and giving us the results.
The problem is aquatone is not upadting therefore their latest app.json (wappalyzer sigs) is almost 2 years old.

Therefore creating our very own fingerprinting is better.

I've linked this around

https://github.com/vincd/wappylyzer/blob/master/wappylyzer.py

**Comment by abdilahrf** [comment]
this was a better option https://github.com/rverton/webanalyze a port of wappalyzer in golang

**Comment by yogeshojha** [comment]
A quick question, is the tech-detect from webanalyze or wappalyzer any better than httpx? Currently reNgine uses https -tech-detect .
