### ISSUE TITLE
Supply API keys for Subdomain Enumeration 

### ISSUE THREAD

**Issue by DhiyaneshGeek** [yogeshojha/rengine#392]
How to supply API Keys for Subfinder?

Is it possible to have a separate tab or location ?

**Comment by yogeshojha** [comment]
Please folllw the official documentation. https://rengine.wiki/pentester/usage/#configurations

**Comment by yahod** [comment]
Hey @yogeshojha 
I suppose the point here was to have to second editor tab for Subfinder since the tool has two config files: 1) basic settings `config.yaml`; 2) API keys for external recon services `provider-config.yaml` [link](https://github.com/projectdiscovery/subfinder#post-installation-instructions).
I'd be glad if you point to the way how I can edit the second one.

**Comment by barbixxxa** [comment]
> Found workaround: In order to update `provider-config.yaml`, directly edit `/var/lib/docker/volumes/rengine_tool_config/_data/subfinder/provider-config.yaml`

https://github.com/yogeshojha/rengine/issues/544
https://github.com/yogeshojha/rengine/issues/590
