### ISSUE TITLE
Can't access rengine after installing.

### ISSUE THREAD

**Issue by itsmeashim** [yogeshojha/rengine#415]
I have installed rengine using make build command and after that make run command. I am using Cloudflare as a nameserver and domain manager for the domain I am going to use for rengine. I am using ubuntu VM from oracle. 

rengine logs:
![image](https://user-images.githubusercontent.com/84639398/125413344-88359ea5-76f6-45aa-aea3-ed71e1cf608b.png)

I am not able to access it neither from the domain nor directly from VM IP.

**Comment by foozzi** [comment]
same problem!

**Comment by TheShooter** [comment]
Same!

**Comment by tomsec** [comment]
I installed the reNgine in Debian distro in WSL and I was also facing the same issue where I wasn't able to access the application. I am not sure if it will work for you or not but it will be worth giving it a try.

Install reNgine by following the same approach as specified in the wiki. Just don't install docker-compose since it will be pre-included with the Docker desktop. Once you are done installing the application then just restart your Docker desktop once from the system tray and then try to execute the "make up" command once again. After that do "ifconfig" the check your IP and access the "https://<IP>:443" to access the application.

Let me know if it works for you.

**Comment by yogeshojha** [comment]
https://rengine.wiki/install/install/
