### ISSUE TITLE
The assets doesn't load after install 

### ISSUE THREAD

**Issue by xElkomy** [yogeshojha/rengine#434]
The assets doesn't load after install 

![ksnip_20210816-023639](https://user-images.githubusercontent.com/46958133/129497668-99bf3766-eafa-458b-bcd1-b8269b2b124d.png)

Any help with that?

**Comment by yogeshojha** [comment]
Can you try with ctrl + shift + r?

**Comment by zombozo12** [comment]
Hi, I got the same problem and please reopen this issue. Tested on Debian 10 and Ubuntu 20.04.

What I did is I took the `docker-compose.dev.yml` only and leave the rest of it. In the docker compose file, I modified some of things like deleted the `proxy` service because I already have Nginx Proxy Manager. First, I got the same result as the OP's screenshot. And then I tweaked the `staticfiles` and `scan_results` volume and changed the owner to `www-data`. Refreshed it again, only the javascripts is loaded, but not the css. I tweaked nginx configuration but nothing changed. And I give up.

This makes me think "maybe my configuration is wrong, and I should do what's on the documentation said". I tried, ends with the same result.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21243980/147729499-17d8c4a0-5a9f-4de8-9ef0-4427a0c57677.png">

**Comment by zombozo12** [comment]
I found the fix, will try to test on forked repo.

**Comment by zombozo12** [comment]
I did, but i recently deleted my server with rengine in it. But perhaps I can redo it again manually. If I can recall, the problem was on `staticfiles` directory (as mentioned above) which was not routed correctly with nginx in the docker. I did some tweak and I can fully use rengine as it should be.

**Comment by ocervell** [comment]
@zombozo12 I think I figured it out, it's just I had removed the `nginx` proxy but it's actually serving the static files so it's needed.

**Comment by zombozo12** [comment]
@ocervell Nice! Do you mind share what you did here to help everyone else who have the same problem? Thank you

**Comment by ocervell** [comment]
Just use the default `docker-compose.yml` file and you should be fine: browse to `https://localhost` instead of `http://localhost:8000` which doesn't serve the static files.

**Comment by zombozo12** [comment]
Huh?? Oh!! I forgot that rengine docker-compose file has nginx in it to proxy pass the rengine. I was so dumb. Thank you for your findings @ocervell
