### ISSUE TITLE
Bug - A second slash is added to the url of a discovered directory/file when clicked/opened

### ISSUE THREAD

**Issue by SiddharthBharadwaj** [yogeshojha/rengine#442]
### Issue Summary
When the user clicks on the any discovered directory or file, a second slash is added to the url. This causes issues in some cases or websites.

### Steps to Reproduce

1. Open scan summary of any target
2. Visit the Directories tab
3. Click on any directory/url
4. Notice the url

eg. If the target is example.com and a directory /files is found. The clicking on the link should open https://example.com/file but it opens https://example.com//file

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no): yes

**Comment by yogeshojha** [comment]
Hi Thanks for reporting, I can help you resolve this, are you willing to send a Pull Request, that way you can also get involved in Open Source Contributing. 

https://github.com/yogeshojha/rengine/blob/0c90f18fd5b3369b18b5de1dabeb2f95db5212bd/web/startScan/templates/startScan/detail_scan.html#L1505

This is where the problem is. 

Most probably in these two 

https://github.com/yogeshojha/rengine/blob/0c90f18fd5b3369b18b5de1dabeb2f95db5212bd/web/startScan/templates/startScan/detail_scan.html#L1521

and 

https://github.com/yogeshojha/rengine/blob/0c90f18fd5b3369b18b5de1dabeb2f95db5212bd/web/startScan/templates/startScan/detail_scan.html#L1524

**Comment by SiddharthBharadwaj** [comment]
Created a PR #443. Please check and let me know everything seems fine.
