### ISSUE TITLE
OpenVAS

### ISSUE THREAD

**Issue by AbacusQ** [yogeshojha/rengine#593]
I would love to see OpenVAS in combination with reNgine. Nuclei is used to look for web vulns, OpenVAS will find network related vulns.

**Comment by psyray** [comment]
Now Nuclei comes really far in scanning (port scan etc ...)
reNgine is more a Web solution than a network solution.
OpenVAS has an already fully packaged VM that could fit to your needs.
https://www.greenbone.net/en/testnow/#toggle-id-3
So, instead of someone would like to add this feature, I don't think OpenVAS integration would be a good idea.
@yogeshojha Your advice ?

**Comment by AnonymousWP** [comment]
I think reNgine's adaptability wouldn't get better from integrating OpenVAS, as it requires more maintenance as well. This is more complicated than with most other scanning tools built into reNgine. Also, like you said, Nuclei is getting better and better and more advanced.
