### ISSUE TITLE
Web login

### ISSUE THREAD

**Issue by deathflash1411** [yogeshojha/rengine#72]
Since most of the people run their recon tools on cloud servers, it would be great to have a web login.

**Comment by yogeshojha** [comment]
This is much needed. This is in the roadmap, and thanks for the suggestion!

**Comment by unl1k3ly** [comment]
if i could suggest, just upstream the gunicorn as a proxy using nginx and leave the auth part for the front end proxy. If you want me, I can do a pull around your docker-compose. Cheers

**Comment by yogeshojha** [comment]
Hi @unl1k3ly 

I have plans to use gunicorn and nginx as a proxy. I already worked on a web login feature. I will release by this week. Login feature was much needed. Can you help me with the gunicorn and nginx part?
It's much needed and as I am busy on integrating couple other features, would really appreciate if you could help me with this.

Thanks
Stay healthy!

**Comment by unl1k3ly** [comment]
Hi @yogeshojha sorry for delay response here... I've being pretty busy theses days :( 

I was looking at your compose and you just need a upsteam your backend into nginx and pass it as a proxy so you fetch from nginx while doing auth.

I really dont want to mess up your config so, I've done in a separate file so you can test and have a look... Although, I think you just did using python engine rather than nginx. Config are the following 

```
upstream backend {
  server 127.0.0.1:8000;
}

server {
    listen 80;

    location / {
        auth_basic "ARE YOU SURE ?";
        auth_basic_user_file /htpasswd;
        # autoindex on;
        proxy_pass http://backend;
    }
}

```

**Comment by cehbikramrock** [comment]
docker exec -it rengine_web_1 python manage.py createsuperuser
not work #HELP me
