### ISSUE TITLE
CIDRs

### ISSUE THREAD

**Issue by iseesec** [yogeshojha/rengine#728]
Adding multiple subnet segment addresses is not supported

For example:

100.100.200.1/24
50.50.50.1/24
177.188.199.1/24

**Comment by ad0nis** [comment]
Seconded. I was excited to see that the interface was starting to support importing IP addresses and subnets instead of just DNS names, however importing every line from a scope file manually is a no-go for me. Would be great to upload a list of CIDR ranges as well as individual IP address, and even hyphenated ranges to cover the breadth of common IP scope formats.

**Comment by psyray** [comment]
Fixed by https://github.com/yogeshojha/rengine/pull/963 with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200

![image](https://github.com/yogeshojha/rengine/assets/1230954/e8f3198c-4beb-4cbd-af59-12b703a9b951)
