### ISSUE TITLE
ERROR: Service 'celery' failed to build : Build failed

### ISSUE THREAD

**Issue by rajesh457** [yogeshojha/rengine#751]
### Issue Summary

While doing the fresh install of rengine on DO VPS, I got this issue

### Steps to Reproduce

1. fresh install of rengine using the official documentation

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes )

### Technical details

```
go: downloading github.com/projectdiscovery/subfinder v2.5.4+incompatible
go: github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest: module github.com/projectdiscovery/subfinder@latest found (v2.5.4+incompatible), but does not contain package github.com/projectdiscovery/subfinder/v2/cmd/subfinder
The command '/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest' returned a non-zero code: 1
ERROR: Service 'celery' failed to build : Build failed
make: *** [Makefile:25: build] Error 1
```

**Comment by maiestro21** [comment]
@rajesh457 inside /web/ folder you have a Dockerfile.
In the Dockerfile you can search for the subfinder line and you can replace at the end "@latest" with a specific one like "fa16e09880d437bbccfe624a6b26ae3e593aecda".

Example:
github.com/projectdiscovery/subfinder/v2/cmd/subfinder@fa16e09880d437bbccfe624a6b26ae3e593aecda 

The issue comes from the changes of the maine branch of subfinder, so you can just wait for a new release if you want.

BR
