### ISSUE TITLE
Feature - Add a way to skip subdomain scan process & use external discovered subdomains lists

### ISSUE THREAD

**Issue by 0xPrial** [yogeshojha/rengine#89]
In import target option we can feed multiple domains in txt list . But if you can add a feature where we can skip the Subdomain scanning part and import a subdomains list from external scanned tools  as there is many other way to gather Subdomains 😇 . Here we can’t skip the Subdomain discovery from scan engine . Hope you will take a look to skip the Subdomain discovery option , so the workflow will be

* Import Subdomains list in txt what discovered by other tools and recon methodology .
* Fetch live domains
* Do port scan
* Takeover scan
* Directory search
* Fetch all urls from wayback, OTX .
* Also if possible add urlscan.io for fetching target data ex: https://twitter.com/prial261/status/1254503609217150976

Cheers

**Comment by yogeshojha** [comment]
This is in the pipeline @prial261 

I am currently working on it. Your suggestions are very much appreciated! Thank you once again

**Comment by yogeshojha** [comment]
Thanks, @prial261 

I have removed the subdomain only scan. Can you please check?


Also, I have added you on contributors.md list as a vote of thanks.

Please continue providing suggestions.

**Comment by yogeshojha** [comment]
This is fixed, a new issue has been created for URLSCAN.IO, which will be worked on.

**Comment by prial261** [comment]
After you removed the subdomain only scan Now I can skip the subdomain discovery part but now if I import target's subdomain list in a txt file and want to do a scan using following scan engine configuration
<img width="456" alt="Screenshot 2020-07-15 at 10 18 22 PM" src="https://user-images.githubusercontent.com/25204004/87569563-1fb72f80-c6e9-11ea-91c4-01d04ccbbdc6.png">

Then I need to click on **Start scan** every subdomain one by one what is not a good idea for such automatic recon tools . Please add a feature so that we can do above configuration scan on all imported subdomain just by one click .

**Comment by yogeshojha** [comment]
You are absolutely right Prial.
But, currently, I am working on couple of other features, I will keep this as a priority and will add the feature soon.

**Comment by Regala** [comment]
Any luck with this feature to able to import our existing domains? 😬

**Comment by yogeshojha** [comment]
Yes @Regala, you mean you got targets and then import subdomains, on that target and continue the scan? This is almost over, v0.6 is coming soon, probably this month end with so many enhancements you all have been asking for.

**Comment by Regala** [comment]
Awesome! 🙏 🙏 🙏

**Comment by yogeshojha** [comment]
I am excited to update you that this is coming :rocket:

This is the flow

1. Initiate a scan
2. Choose the scan engine
![image](https://user-images.githubusercontent.com/17223002/120899448-743f0280-c64d-11eb-9e01-e3cc8754b1aa.png)
3. Import subdomains from an external source
![image](https://user-images.githubusercontent.com/17223002/120899478-8faa0d80-c64d-11eb-9006-7c33f8095223.png)

If the imported subdomains are not of the domain that you are scanning, they will be ignored.

**Comment by Regala** [comment]
This looks great @yogeshojha , thank you! Excited to try it out.

(unrelated) quick question since I have you and other people might be interested:
- Is there any simple/basica API we can use? I'm interested to basically sending data from my tools and leaverage Rengine for visualization of results
- 
Cheers!

**Comment by yogeshojha** [comment]
I am excited to release this as well @Regala.
Working super hard  from past 5 months, and We have so many exciting features coming up, Scan comparision, newly added/removed subdomain/endpoints, ability to find interesting subdomains/endpoints, OSINT, huge improvement in scans, upload custom nuclei patterns, and also now you've GF as well, upload your custom gf pattern and so many exciting features. Closing this soon. Target is June 23, let's see how it goes.

Plus, we do have API, infact everything works in the DRF, I have also worked on the documentation, so I assuee you, this is coming.

**Comment by Regala** [comment]
Beautiful!!! Great job 💚💚💚

**Comment by yogeshojha** [comment]
This is released. Thanks

**Comment by yogeshojha** [comment]
https://rengine.wiki/usage/scan_target/#importing-subdomains
